apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DEMO_URL
          value: google.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1
data:
  DEMO_URL: google.com
  ENV: demo-env
---
apiVersion: v1
kind: Pod
metadata:
  name: env1
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: app1
---
apiVersion: v1
kind: Secret
metadata:
  name: secret1
data:
  DEMO_URL: Z29vZ2xlLmNvbQ==
  ENV: ZGVtby1lbnY=
---
apiVersion: v1
kind: Pod
metadata:
  name: env2
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: secret1



