#apiVersion: apps/v1
#kind: ReplicaSet
#metadata:
#  name: frontend
#  labels:
#    app: guestbook
#    tier: frontend
#spec:
#  # modify replicas according to your case
#  replicas: 1
#  selector:
#    matchLabels:
#      tier: frontend
#  template:
#    metadata:
#      labels:
#        tier: frontend
#    spec:
#      containers:
#      - name: php-redis
#        image: gcr.io/google_samples/gb-frontend:v3
#        env:
#          - name: DEMO
#            value: demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        env:
          - name: DEMO
            value: example.google.com

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cip
spec:
  type: ClusterIP
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-np
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000